version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: web-ext
    versions:
    - 6.0.0
  - dependency-name: bl
    versions:
    - 4.1.0
  - dependency-name: "@cliqz/adblocker-webextension"
    versions:
    - 1.20.1
    - 1.20.2
  - dependency-name: "@cliqz/adblocker-webextension-cosmetics"
    versions:
    - 1.20.1
    - 1.20.2
  - dependency-name: webextension-polyfill-ts
    versions:
    - 0.24.0
    - 0.25.0
  - dependency-name: "@rollup/plugin-typescript"
    versions:
    - 8.1.1
    - 8.2.0
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.1
    - 11.2.0
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.2
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.1.0
  - dependency-name: idb-keyval
    versions:
    - 5.0.2
